// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BxBxDotsHorizontal: typeof import('~icons/bx/bx-dots-horizontal')['default']
    BxBxPlus: typeof import('~icons/bx/bx-plus')['default']
    BxBxsTrash: typeof import('~icons/bx/bxs-trash')['default']
    BxBxTrash: typeof import('~icons/bx/bx-trash')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    EcNode: typeof import('C:/Users/mouettxy/Desktop/projects/ec-builder/src/components/ec-node.vue')['default']
    EcNodeAddOption: typeof import('C:/Users/mouettxy/Desktop/projects/ec-builder/src/components/ec-node-add-option.vue')['default']
    EcNodeOption: typeof import('C:/Users/mouettxy/Desktop/projects/ec-builder/src/components/ec-node-option.vue')['default']
    Footer: typeof import('C:/Users/mouettxy/Desktop/projects/ec-builder/src/components/Footer.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NModal: typeof import('naive-ui')['NModal']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
  }
}

export { }
